spring:
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/legou
    username: root
    password: 123456
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/legou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.legou.domain,cn.itsource.legou.query
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/legou_test
    username: root
    password: 123456
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:cn/itsource/legou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.legou.domain,cn.itsource.legou.query
