spring:
  profiles:
    active: dev
---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
    profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/legou"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**
    common.serviceId: common-privoder
    common.path: /common/**
---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
    profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true
zuul:
  prefix: "/legou"
  ignored-services: "*"
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**
    common.serviceId: common-privoder
    common.path: /common/**
